apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-deploy
  namespace: tier3-apps
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageValue: 50m
        type: AverageValue
    type: Resource
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deploy
status:
  currentMetrics: null
  desiredReplicas: 0
