pipeline {
    agent any

stages {

stage('clone repo') {
    steps {
        git branch: 'main', url: 'https://github.com/dev-shreyas/tier-3-eks-iac-app.git'
    }
}

stage('Build Docker Images') {
    steps {
        sh '''
            docker compose -f app/docker-compose.yaml build
        '''
    }
}

stage('Deploy docker containers locally using docker compose') {
    steps {
        sh '''
            docker compose -f app/docker-compose.yaml down || true
            docker compose -f app/docker-compose.yaml up -d --build
        '''
            }
        }
    }
}